import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import type{CreateInvoiceInput,LightningInvoice,LightningReceiveProvider,Bolt12ReceiveProvider}from'@cherito/bitcoin-sdk';import{Repository}from'../src/persistence/repository.js';import{PaymentService}from'../src/services/payment-service.js';import{loadConfig}from'../src/config.js'
function mkdb() {
  return ':memory:'
}
class LndMock implements LightningReceiveProvider{creates=0;callback?:((i:LightningInvoice)=>void);offline=false;auth=false;tls=false;async getCapabilities(){return{bolt11Receive:true,bolt12Receive:false,invoiceStreaming:true,provider:'lnd'as const}}async getNodeInfo(){if(this.offline)throw new Error('offline');return{network:'regtest'as const}}async createInvoice(i:CreateInvoiceInput){if(this.offline)throw new Error('offline');if(this.auth)throw new Error('macaroon');if(this.tls)throw new Error('certificate');this.creates++;return{providerInvoiceId:'1',paymentHash:'ab'.repeat(32),paymentRequest:'lnbcrt1realmock',amountSats:i.amountSats,expiresAt:new Date(Date.now()+900000).toISOString(),state:'pending'as const}}async getInvoice(){throw new Error('unused')}async subscribeToInvoice(_h:string,cb:(i:LightningInvoice)=>void){this.callback=cb;return async()=>{}}}
class BoltMock implements Bolt12ReceiveProvider{constructor(private fail=false){}async getCapabilities(){return{bolt11Receive:true,bolt12Receive:true,invoiceStreaming:true,provider:'lndk'as const}}async createOffer(i:{amountSats:bigint}){if(this.fail)throw new Error('LNDK unavailable');return{offerId:'offer1',offer:'lno1officialmock',amountSats:i.amountSats}}}
function fixture(bolt?:Bolt12ReceiveProvider){const database=mkdb(),config=loadConfig({NODE_ENV:'test',LND_REST_URL:'https://localhost:8080',LND_TLS_CERT_BASE64:Buffer.from('cert').toString('base64'),LND_MACAROON_HEX:'aa',DATABASE_URL:database}),lnd=new LndMock(),repo=new Repository(database);return{config,lnd,repo,service:new PaymentService(lnd,bolt,repo,config)}}
test('3 creates an invoice with server price; 12 browser price cannot override it',async()=>{const f=fixture(),r=await f.service.create('cherito-coffee-001',2,crypto.randomUUID());assert.equal(r.amountSats,'50000');assert.equal(f.lnd.creates,1)})
test('5 settled confirms; 14 repeated settlement is idempotent',async()=>{const f=fixture(),r=await f.service.create('cherito-coffee-001',1,crypto.randomUUID()),i={providerInvoiceId:'1',paymentHash:'ab'.repeat(32),paymentRequest:'lnbcrt1realmock',amountSats:25000n,expiresAt:r.expiresAt,state:'settled'as const,settledAt:new Date().toISOString()};f.lnd.callback?.(i);f.lnd.callback?.(i);assert.equal(f.service.authorize(r.checkoutSessionId,r.statusToken)?.state,'succeeded')})
test('7 disconnected node; 8 invalid macaroon; 9 invalid certificate propagate',async()=>{for(const mode of['offline','auth','tls']as const){const f=fixture();f.lnd[mode]=true;await assert.rejects(()=>f.service.create('cherito-coffee-001',1,crypto.randomUUID()))}})
test('10 duplicate key returns same checkout; 11 changed payload conflicts',async()=>{const f=fixture(),key=crypto.randomUUID(),a=await f.service.create('cherito-coffee-001',1,key),b=await f.service.create('cherito-coffee-001',1,key);assert.equal(a.checkoutSessionId,b.checkoutSessionId);assert.equal(a.statusToken,b.statusToken);assert.equal(f.lnd.creates,1);await assert.rejects(()=>f.service.create('cherito-coffee-001',2,key),/conflict/)})
test('13 incorrect status token is rejected',async()=>{const f=fixture(),r=await f.service.create('cherito-coffee-001',1,crypto.randomUUID());assert.equal(f.service.authorize(r.checkoutSessionId,'wrong'),undefined)})
test('15 BOLT12 disabled',async()=>{const f=fixture();await assert.rejects(()=>f.service.createOffer('cherito-coffee-001'),(e:unknown)=>(e as{code?:string}).code==='BOLT12_NOT_CONFIGURED')})
test('16 LNDK failure does not affect BOLT11',async()=>{const f=fixture(new BoltMock(true));await assert.rejects(()=>f.service.createOffer('cherito-coffee-001'));assert.equal((await f.service.create('cherito-coffee-001',1,crypto.randomUUID())).state,'requires_payment')})
test('17 responses and 18 logs contain no credential material',()=>{const source=readFileSync(new URL('../src/server.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/send\([^)]*(macaroon|certificate)/i);assert.match(source,/redact:/)})
test('unsafe privileged configuration is refused',()=>{for(const name of['ADMIN_MACAROON','SEED','XPRV','PRIVATE_KEY'])assert.throws(()=>loadConfig({[name]:'x'}),/forbidden/)})
